# Generated by Django 4.1 on 2023-03-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema_Ebooking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="apartNumber",
            field=models.TextField(blank=True, null=True),
        ),
    ]
