# Generated by Django 4.1.7 on 2023-03-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_Ebooking', '0003_remove_user_cardname_remove_user_ccnum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cardname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
