# Generated by Django 4.1.7 on 2023-03-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_Ebooking', '0005_alter_card_cvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
