# Generated by Django 4.1.7 on 2023-03-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_Ebooking', '0006_alter_card_cvc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('category1', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Biography', 'Biography'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Filmnoir', 'Film-Noir'), ('Gameshow', 'Game-show'), ('History', 'History'), ('Horror', 'Horror'), ('Music', 'Music'), ('Musical', 'Musical'), ('Mystery', 'Mystery'), ('News', 'News'), ('Realitytv', 'Reality-TV'), ('Romance', 'Romance'), ('Scifi', 'Sci-Fi'), ('Sport', 'Sport'), ('Talkshow', 'Talk-Show'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western')], max_length=25)),
                ('category2', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Biography', 'Biography'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Filmnoir', 'Film-Noir'), ('Gameshow', 'Game-show'), ('History', 'History'), ('Horror', 'Horror'), ('Music', 'Music'), ('Musical', 'Musical'), ('Mystery', 'Mystery'), ('News', 'News'), ('Realitytv', 'Reality-TV'), ('Romance', 'Romance'), ('Scifi', 'Sci-Fi'), ('Sport', 'Sport'), ('Talkshow', 'Talk-Show'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western')], default='', max_length=25)),
                ('category3', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Biography', 'Biography'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Filmnoir', 'Film-Noir'), ('Gameshow', 'Game-show'), ('History', 'History'), ('Horror', 'Horror'), ('Music', 'Music'), ('Musical', 'Musical'), ('Mystery', 'Mystery'), ('News', 'News'), ('Realitytv', 'Reality-TV'), ('Romance', 'Romance'), ('Scifi', 'Sci-Fi'), ('Sport', 'Sport'), ('Talkshow', 'Talk-Show'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western')], default='', max_length=25)),
                ('description', models.TextField(default='', max_length=300)),
                ('review', models.URLField(default='')),
                ('rating', models.CharField(choices=[('G', 'G General Audiences'), ('PG', 'PG Parental Guidance Suggested'), ('PG-13', 'PG-13 Parents Strongly Cautioned'), ('R', 'R Restricted'), ('NC-17', 'NC-17 Adults Only')], default='', max_length=100)),
                ('status', models.CharField(choices=[('Now Playing', 'Now Playing'), ('Upcoming', 'Upcoming')], default='', max_length=50)),
                ('cast', models.CharField(default='', max_length=200)),
                ('director', models.CharField(default='', max_length=100)),
                ('producer', models.CharField(default='', max_length=100)),
                ('poster', models.ImageField(default='', upload_to='images/')),
                ('trailer', models.URLField(default='')),
                ('releasedate', models.DateField(blank=True, default=False, null=True)),
                ('archived', models.BooleanField(blank=True, default=False, help_text='If value is yes then it wont be visible on the booking portal', null=True)),
                ('year', models.CharField(default='', max_length=5)),
                ('imdb', models.CharField(default='', max_length=6)),
            ],
        ),
    ]
