# Generated by Django 4.1 on 2023-03-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema_Ebooking", "0007_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="cvc",
        ),
        migrations.RemoveField(
            model_name="card",
            name="last_four",
        ),
        migrations.AddField(
            model_name="card",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
