# Generated by Django 4.1 on 2023-03-21 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cinema_Ebooking", "0008_remove_card_cvc_remove_card_last_four_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="expiry_date",
        ),
        migrations.AddField(
            model_name="card",
            name="cvc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="last_four",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.CreateModel(
            name="UserCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cardname", models.CharField(blank=True, max_length=100, null=True)),
                ("cardnum", models.CharField(blank=True, max_length=150, null=True)),
                ("valid", models.TextField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, default=False, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
