# Generated by Django 4.1 on 2023-03-21 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cinema_Ebooking", "0010_delete_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ccnum", models.CharField(blank=True, max_length=150, null=True)),
                ("valid", models.TextField(blank=True, null=True)),
                ("last_four", models.CharField(blank=True, max_length=4, null=True)),
                ("cvc", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserCard",
        ),
    ]
