# Generated by Django 4.1 on 2023-03-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema_Ebooking", "0011_card_delete_usercard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="ccnum",
            new_name="cardNum",
        ),
        migrations.RenameField(
            model_name="card",
            old_name="valid",
            new_name="expiryDate",
        ),
        migrations.RemoveField(
            model_name="card",
            name="cvc",
        ),
        migrations.AddField(
            model_name="card",
            name="cardHolderName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
