# Generated by Django 4.1.7 on 2023-04-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_Ebooking', '0017_remove_seat_seat_01_remove_seat_seat_02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_booked',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_selected',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
