# Generated by Django 4.1.7 on 2023-04-13 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_Ebooking', '0018_alter_seat_seat_booked_alter_seat_seat_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='valid_from',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_available',
            field=models.CharField(default='1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50', max_length=200),
        ),
    ]
