# Generated by Django 4.1 on 2023-04-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema_Ebooking", "0020_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickets",
            name="refernceNumber",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
