# Generated by Django 4.1 on 2023-04-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema_Ebooking", "0021_tickets_referncenumber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tickets",
            old_name="refernceNumber",
            new_name="referenceNumber",
        ),
    ]
