# Generated by Django 4.1.7 on 2023-04-25 02:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_Ebooking', '0022_rename_referncenumber_tickets_referencenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('bookingID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tickets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema_Ebooking.tickets')),
            ],
        ),
    ]
